# Generated by Django 3.0 on 2022-03-30 07:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220329_1724'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0002_auto_20220311_1733'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('escalator_note', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=200)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='main.Message')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
