# Generated by Django 3.0 on 2022-03-30 13:36

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20220329_1724'),
        ('report', '0003_auto_20220330_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedcase',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to='main.Message'),
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('situation_report', models.TextField()),
                ('image_url1', models.URLField(blank=True, null=True)),
                ('image_url2', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='report.AssignedCase')),
            ],
        ),
    ]
