# Generated by Django 3.0 on 2022-07-05 01:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('report', '0003_requestsupport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsupport',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requested_support', to=settings.AUTH_USER_MODEL),
        ),
    ]
