# Generated by Django 3.0 on 2023-12-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_assignedcase_escalator'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedcase',
            name='arrived_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignedcase',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='assignedcase',
            name='responded_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='requestsupport',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
