# Generated by Django 3.0 on 2022-03-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='escalator',
            new_name='agency',
        ),
    ]
