# Generated by Django 3.0 on 2022-02-11 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='business_name',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_deleted',
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(max_length=250, null=True, verbose_name='gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='local_gov',
            field=models.CharField(max_length=250, null=True, verbose_name='local government'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('escalator', 'Escalator'), ('agent', 'Agent'), ('first_responder', 'First Responder'), ('admin', 'Admin')], max_length=250, verbose_name='role'),
        ),
    ]
