# Generated by Django 3.0 on 2022-05-23 18:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('acronym', models.CharField(max_length=255, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name_of_reporter', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+2341234567890'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('victim_name', models.CharField(blank=True, max_length=300, null=True)),
                ('victim_gender', models.CharField(blank=True, max_length=300, null=True)),
                ('victim_age', models.CharField(blank=True, max_length=300, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('escalated', 'Escalated'), ('assigned', 'Assigned'), ('completed', 'Completed')], default='pending', max_length=300)),
                ('category', models.CharField(choices=[('rape', 'Rape'), ('child_abuse', 'Child Abuse'), ('domestic_violence', 'Domestic Violence'), ('missing_person', 'Missing Person'), ('dead_body', 'Dead Body'), ('collapsed_building', 'Collapsed Building'), ('accident', 'Accident'), ('fight', 'Fight'), ('fire_outbreak', 'Fire Outbreak')], max_length=300)),
                ('description', models.TextField()),
                ('address', models.TextField(blank=True, null=True)),
                ('incident_address', models.TextField(blank=True, null=True)),
                ('image_url1', models.URLField(blank=True, null=True)),
                ('image_url2', models.URLField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('last_seen_detail', models.TextField(blank=True, null=True)),
                ('is_emergency', models.BooleanField(default=False)),
                ('agent_note', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('provider', models.CharField(choices=[('whatsapp', 'Whatsapp'), ('call', 'Call')], default='whatsapp', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('agencies', models.ManyToManyField(blank=True, related_name='messages', to='main.Agency')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
