# Generated by Django 3.0 on 2022-02-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='address',
            field=models.TextField(blank=True, null=True),
        ),
    ]
