# Generated by Django 3.0 on 2022-03-11 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='escalators',
            field=models.ManyToManyField(related_name='messages', to='main.Escalator'),
        ),
    ]
