# Generated by Django 3.0 on 2022-02-21 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_whatsappmessage_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappmessage',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
