# Generated by Django 3.0 on 2022-03-17 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220317_1405'),
        ('main', '0003_auto_20220311_1538'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Escalator',
            new_name='Agency',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='escalators',
            new_name='agencies',
        ),
    ]
