# Generated by Django 3.0 on 2022-06-14 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_answer_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.Issue'),
        ),
    ]
