# Generated by Django 3.0 on 2022-03-29 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_auto_20220317_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='provider',
            field=models.CharField(choices=[('whatsapp', 'Whatsapp'), ('call', 'call')], default='whatsapp', max_length=255),
        ),
    ]
