# Generated by Django 3.0 on 2022-08-22 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_question_is_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='local_gov',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
