# Generated by Django 3.0 on 2022-08-31 12:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_message_local_gov'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='agencies',
        ),
        migrations.CreateModel(
            name='EmergencyCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(max_length=255, unique=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('agency', models.ManyToManyField(related_name='codes', to='main.Agency')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='emergency_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_codes', to='main.EmergencyCode'),
        ),
    ]
