# Generated by Django 3.0 on 2022-08-31 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20220831_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycode',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
