# Generated by Django 3.0 on 2022-10-04 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220831_2150'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='landmark',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('escalated', 'Escalated'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('archived', 'Archived')], default='pending', max_length=300),
        ),
    ]
