# Generated by Django 3.0 on 2022-10-20 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20221012_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='question_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='incident',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='main.Issue'),
        ),
        migrations.AddField(
            model_name='question',
            name='flow_num',
            field=models.IntegerField(null=True),
        ),
    ]
