# Generated by Django 3.0 on 2022-10-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20221020_0741'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='question_title',
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
