# Generated by Django 3.0 on 2023-02-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20221024_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_archived',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='date_escalated',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
