# Generated by Django 3.0 on 2023-07-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20230720_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='emergency_code',
            field=models.ManyToManyField(blank=True, related_name='emergency_codes', to='main.EmergencyCode'),
        ),
    ]
