# Generated by Django 3.0 on 2023-08-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20230720_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='category',
            field=models.CharField(blank=True, choices=[('emergency', 'Emergency'), ('non_emergency', 'Non-Emergency'), ('hoax', 'Hoax'), ('nuisance', 'Nuisance')], max_length=100, null=True),
        ),
    ]
